### PR TITLE
fix(gemini): tool property mapping

### LINKED ISSUE #350: ObjectSchema should not include additionalProperties by default or allow disabling it completely
When using Prism\Prism\Schema\ObjectSchema with Gemini, Prism sends an additionalProperties key in the JSON schema, which causes Gemini to fail with:

`Invalid JSON payload received. Unknown name "additionalProperties" at 'tools.function_declarations[0].parameters.properties[0].value'`

### PR DESCRIPTION
**Pull request by ChrisB-TL**
## Description

Fixes #350 and #375.

### CODE REVIEW

File: tests/Providers/Gemini/ToolTest.php [hunk 1]
```diff
@@ -5,22 +5,46 @@
...
+        ->withObjectParameter(
+            'options',
+            'additional options',
+            [
+                new StringSchema('option1', 'description for option1'),
+            ]
+        )
         ->using(fn (): string => '[Search results]');
 
+    ray(ToolMap::map([$tool]));
```
Comment (sixlive) [inline tests/Providers/Gemini/ToolTest.php:25]: Can probably remove this.

**Review by sixlive — CHANGES_REQUESTED** [review]
Looks good. Need to remove debugging

File: tests/Providers/Gemini/ToolTest.php (hunk 1 above)
Comment (ChrisB-TL) [reply tests/Providers/Gemini/ToolTest.php]: Whoops!

**Review by sixlive — APPROVED** [review]
